MODULE KINDS
INTEGER,PARAMETER :: KD=8
REAL(KIND=KD) :: A,B,C,D,EXACT,H
INTEGER :: ITER
END MODULE KINDS
!--------
PROGRAM DRV_DERIV_NUM
USE KINDS
IMPLICIT REAL(KIND=KD) (A-H,O-Z)
INTEGER :: REPEAT
EXTERNAL DERIV_NUM,F
!
LOOP: DO
PRINT*,’ A, B, C, D ? ’
READ*,A,B,C,D
PRINT*,’ ABSOLUTE TOLERANCE, RELATIVE TOLERANCE, ITERMAX ? ’
READ*,ATOL,RTOL,ITERMAX
PRINT*,’ X, H0 ? ’
READ*,X,H0
VALUE=DERIV_NUM(F,X,H0,ATOL,RTOL,ITERMAX,IFLAG)
PRINT*
PRINT*,’ NUMERICAL VALUE
PRINT*,’ EXACT VALUE
= ’,VALUE
= ’,EXACT
PRINT*,’ PERCENT DIFFERENCE = ’,100*ABS((VALUE-EXACT)/EXACT)
PRINT*,’ IFLAG
= ’,IFLAG
IF (IFLAG > 0) THEN
ITERATIONS=ITER
H_USED=H
ELSE
ITERATIONS=ITER-1
H_USED=2*H
END IF
PRINT*,’ ITERATIONS
PRINT*,’ H USED
= ’,ITERATIONS
= ’,H_USED
PRINT*
PRINT*,’ REPEAT: Y/N-> 1/0 ? ’
READ*,REPEAT
IF (REPEAT==0) THEN
EXIT LOOP
ELSE
CYCLE LOOP
END IF
END DO LOOP
END PROGRAM DRV_DERIV_NUM
!--------
FUNCTION DERIV_NUM(F,X,H0,ATOL,RTOL,ITERMAX,IFLAG)
USE KINDS
IMPLICIT REAL(KIND=KD) (A-H,O-Z)
EXTERNAL F
!
H=H0
D0=(F(X+H)-F(X))/H
IF (ITERMAX==0) THEN
IFLAG=1
DERIV_NUM=D0
RETURN
END IF
H=H/2
D1=(F(X+H)-F(X))/H
IF (ITERMAX==1) THEN
IFLAG=1
DERIV_NUM=D1
RETURN
END IF
!
ITER=1
DIFNOW=ABS(D1-D0)
LOOP: DO
ITER=ITER+1
D0=D1
DIFPRE=DIFNOW
H=H/2
D1=(F(X+H)-F(X))/H
DIFNOW=ABS(D1-D0)
IF (DIFNOW < DIFPRE) THEN
IF (DIFNOW < RTOL*ABS(D1)+ATOL) THEN
IFLAG=1
DERIV_NUM=D1
RETURN
END IF
IF (ITER >= ITERMAX) THEN
IFLAG=2
DERIV_NUM=D1
RETURN
END IF
CYCLE LOOP
ELSE
IFLAG=0
DERIV_NUM=D0
RETURN
END IF
END DO LOOP
END FUNCTION DERIV_NUM
!--------
FUNCTION F(X)
USE KINDS
IMPLICIT REAL(KIND=KD) (A-H,O-Z)
F=A+B*X+C*X**2+D*X**3
EXACT=B+2*C*X+3*D*X**2
END FUNCTION F
!--------